[project]
name = "linear-gaussian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "auggiemarignier", email = "auggie.marignier@earth.ox.ac.uk" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
linear-gaussian = "linear_gaussian:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"
