[project]
name = "sddr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "auggiemarignier", email = "auggie.marignier@earth.ox.ac.uk" }
]
requires-python = ">=3.12"
dependencies = [
    "emcee>=3.1.6",
    "harmonic>=1.3.1",
]

[project.scripts]
sddr = "sddr:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"
